Traceback (most recent call last):
  File "tests/bugs/issue_21/test_ozone_max_autoreg_5.py", line 10, in <module>
    import ForecastEngine as autof
ImportError: No module named 'ForecastEngine'
